# TODO rivedere bene come poter creare immagine da altra imamgine
FROM mariadb:latest
#FROM openjdk:8-jre-alpine
EXPOSE 3307
#EXPOSE 8080
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
#COPY target/docker1.jar app.jar
RUN addgroup -S app && adduser -S app -G app
USER app
ENTRYPOINT ["java","-jar","/app.jar"]
