GET http://localhost:8080/API/courses/

###
GET http://localhost:8080/api/item?id=99
Accept: application/json

###
POST http://localhost:8080/api/users/professors
Content-Type: application/json

{
  "test": "testt"
}

###
POST http://localhost:8080/api/images
Content-Type: multipart/form-data

{}

###
POST http://localhost:8080/api/images/test?test=email@a
Content-Type: text/plain

test

